### ISSUE TITLE
slurm profile

### ISSUE THREAD

**Issue by EricFournier3** [phac-nml/snvphylnfc#24]
### Description of feature

Hi,

is it possible to add a slurm profile in .nextflow/assets/phac-nml/snvphylnfc/nextflow.config so that we can run on cluster?

Thanks
Eric

**Comment by apetkau** [comment]
You should be able to write and pass your own configuration to Nextflow to run via slurm by writing a `slurm.conf` file like:

**slurm.conf**
```
process {
    executor = 'slurm'
}
```

Then, you can run the pipeline and pass this extra configuration like:

```bash
nextflow run phac-nml/snvphylnfc -c slurm.conf ...
```

Since we don't know the exact settings you want for SLURM, I would rather avoid including this in the pipeline code itself.

You can also look through the nf-core documentation on customizing configuration of pipelines: https://nf-co.re/docs/usage/getting_started/configuration#custom-configuration-files

**Comment by EricFournier3** [comment]
thanks @apetkau  this would do the job
